# Generated by Django 3.0.8 on 2020-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0002_auto_20200715_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='gambar/'),
        ),
    ]
