# Generated by Django 3.0.8 on 2020-07-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0003_auto_20200715_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageuploader_profile',
        ),
    ]
