# Generated by Django 3.0.8 on 2020-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0004_remove_image_imageuploader_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deskripsi',
            field=models.TextField(default='keterangan', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='harga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='kategori',
            field=models.CharField(choices=[('daging', 'Daging'), ('sayur', 'Sayur'), ('bumbu', 'Bumbu'), ('bawang', 'Bawang'), ('cabe', 'Cabe'), ('buah', 'Buah'), ('peralatan', 'peralatan')], default='Sayur', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='nama',
            field=models.CharField(default='Produk', max_length=200),
        ),
    ]
