# Generated by Django 3.0.8 on 2020-07-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0005_auto_20200716_0201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Barang',
        ),
    ]
