# Generated by Django 3.0.8 on 2020-07-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0006_auto_20200716_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='deskripsi2',
            field=models.TextField(default='keterangan', max_length=500),
        ),
    ]
