# Generated by Django 3.0.8 on 2020-07-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0008_auto_20200716_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='image',
            field=models.ImageField(upload_to='gambar/'),
        ),
    ]
