# Generated by Django 3.0.8 on 2020-07-18 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0009_auto_20200718_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gambar')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasarkita.Barang')),
            ],
        ),
    ]
