# Generated by Django 3.0.8 on 2020-07-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0010_auto_20200718_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='alamat',
            field=models.TextField(default='alamat', max_length=500),
        ),
        migrations.AddField(
            model_name='barang',
            name='alamat2',
            field=models.TextField(default='alamat', max_length=500),
        ),
    ]
