# Generated by Django 3.0.8 on 2020-07-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0011_auto_20200720_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='barang',
        ),
        migrations.AddField(
            model_name='barang',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pasarkita.Images'),
        ),
    ]
