# Generated by Django 3.0.8 on 2020-07-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0012_auto_20200720_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasarkita.Images'),
        ),
    ]
