# Generated by Django 3.0.8 on 2020-07-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0013_auto_20200720_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='images',
            new_name='image',
        ),
    ]
