# Generated by Django 3.0.8 on 2020-07-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0014_auto_20200720_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasarkita.Images'),
        ),
    ]
