# Generated by Django 3.0.8 on 2020-07-21 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0015_auto_20200720_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='image',
        ),
    ]
