# Generated by Django 3.0.8 on 2020-07-21 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0016_remove_barang_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasarkita.Barang'),
        ),
    ]
