# Generated by Django 3.0.8 on 2020-07-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarkita', '0019_auto_20200721_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='image',
            field=models.ImageField(default='default.png', upload_to='gambar'),
        ),
    ]
